### ISSUE TITLE
Create CI/CD pipeline 

### ISSUE THREAD

**Issue by lukejs01** [bluepicnic/SQA-Assignment-2---Number-System-Converter#16]
Create CI/CD pipeline to run automated tests and test code coverage

**Comment by bluepicnic** [comment]
Pipelines have been added to actions with clear notation. Will test as we go along and document processes in code

**Comment by bluepicnic** [comment]
Added jsdom test environment to both workflows, as the default environment did not recognise our code, and is not included by default in the default Jest installation.
